# Generated by Django 5.1 on 2024-08-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Custemer', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_status', models.ImageField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERD'), (4, 'ORDER_REJECTED')], default=0, upload_to='')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order', to='Custemer.custemer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Added_item', to='Order.order')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_item', to='Products.product')),
            ],
        ),
    ]
