# Generated by Django 5.1 on 2024-08-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Custemer', '0001_initial'),
        ('Products', '0006_rename_price_product_new_price_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.FloatField(default=0)),
                ('Order_status', models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERD'), (4, 'ORDER_REJECTED')], default=0)),
                ('Delete_Status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order', to='Custemer.custemer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_item', to='Order.order')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_cart', to='Products.product')),
            ],
        ),
    ]
