# Generated by Django 5.1 on 2024-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='\\meadia')),
                ('Priority', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
            ],
        ),
    ]
